name: SAST com SonarCloud (CLI)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sonarcloud-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # 1) Instala o SonarScanner CLI
      - name: Install SonarScanner CLI
        run: |
          curl -sSLo sonar-scanner.zip \
            https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner.zip
          echo "${{ github.workspace }}/sonar-scanner-4.7.0-2747-linux/bin" >> $GITHUB_PATH

      # 2) Cria um sonar-project.properties apontando para SonarCloud
      - name: Create sonar-project.properties
        run: |
          cat <<EOF > sonar-project.properties
          sonar.organization=lucasreinaldo-bash
          sonar.projectKey=lucasreinaldo-bash_edu-api
          sonar.host.url=https://sonarcloud.io
          sonar.sources=.
          EOF

      # 3) Executa o scanner apontando pro token
      - name: Run SonarScanner
        env:
          SONAR_TOKEN: b1604021217df1bd73cdbe454f6df7964bbce943
            
        run: |
          sonar-scanner \
            b1604021217df1bd73cdbe454f6df7964bbce943 \
            -Djava.net.preferIPv4Stack=true
